GET http://localhost:3000/characters

###


POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Jasmine",
    "password": "Aladdin"
}

###

PUT http://localhost:3000/characters/5eb45b983e41f962754e16ac
Content-Type: application/json

{
 "name": "Jasmine",
 "movie": "Aladdin",
 "bestFriend": "Aladdin"
}

###
DELETE http://localhost:3000/characters/5eb45b983e41f962754e16ac
