GET http://localhost:3000/users

###


POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "emmbla",
 "password": "kaffe"
}

###

PUT http://localhost:3000/users/5eb40fd37e36943a8862d465
Content-Type: application/json

{
 "name": "trezzan",
 "password": "kaffe"
}

###
DELETE http://localhost:3000/users/5eb40fd37e36943a8862d465
