GET http://localhost:3000/characters/5ebbeeb82624be44eccf8ba5

###

POST http://localhost:3000/characters/
Content-Type: application/json

{
    "name": "Moln",
    "movie": "Vind",
    "bestFriend": "Vatten",
    "userId": "5ebbeeb82624be44eccf8ba5"
}

###

PUT http://localhost:3000/characters/5ebe93e5164a0525f0cae997
Content-Type: application/json

{
    "name": "Lightning McQueen",
    "movie": "Cars",
    "bestFriend": "Mater",
    "user": "5ebbf1272954922b3ce7c0df"
}

###

DELETE http://localhost:3000/characters/5ebdb391ca067b4b7888dc98

