GET http://localhost:3000/characters

###

POST http://localhost:3000/characters
Content-Type: application/json

{
    "name": "Tiger",
    "movie": "Winnie The Poh",
    "bestFriend": "Piglet",
    "user": "5ebbf1272954922b3ce7c0df"
}

###

PUT http://localhost:3000/characters/5eb3e4553a0fcc8d00be45ac
Content-Type: application/json

{
    "name": "Jasmine",
    "movie": "Aladdin",
    "bestFriend": "Aladdi",
    "user": "5ebbf1272954922b3ce7c0df"
}

###

DELETE http://localhost:3000/characters/5ebdb391ca067b4b7888dc98

